### ISSUE TITLE
Add possibility to keep spaces

### ISSUE THREAD

**Issue by DrVanScott** [liderman/leveldb-cli#1]
Currently it is impossible to work with keys containing space character.

Please either add a possibility to "mask" space characters to keep, or add an option to add an alternative delimiter, e,g, "-d ;" (show;prefix;some key with space)

**Comment by liderman** [comment]
Hi,
I added the ability to escape quotes.
Example:
```bash
set "key 1" "value 1"
```
or
```bash
set "key \"2" value2
```
