### ISSUE TITLE
Non-printable characters are not indicated / supported

### ISSUE THREAD

**Issue by cyradotpink** [liderman/leveldb-cli#4]
You may or not actually care about this, as it's kind of a niche problem, but this CLI currently makes no attempts to deal with non-printable characters. I think it would be neat if, at the very least, non-printable characters in keys (and values) were somehow indicated to the user. (Chromium, for example, uses non-printable characters as delimiters in its localstorage LevelDB store)\
\
Feel free to completely ignore this issue.

**Comment by liderman** [comment]
In the case of Chromium, things are much more complicated:
https://stackoverflow.com/questions/35074659/how-to-access-google-chromes-indexeddb-leveldb-files

To open leveldb created in Chromium need to implement custom comparator.

**Comment by cyradotpink** [comment]
The linked thread is about IndexedDB in Chromium. The way it implements LocalStorage is not as complicated. (Your CLI is able to read the LocalStorage LevelDB just fine!) The only reason I'm suggesting the indicating of non-printable characters is to avoid situations where a user may become confused as to why they can't use the LevelDB keys as returned when listing entries from a store, due to non-printable characters not being indicated or displayed at all.

**Comment by tmartincpp** [comment]
Same here, can't use this tool because of non printable characters, too bad because it seems really nice apart from that.

**Comment by liderman** [comment]
@tmartincpp please can attach
1) example file with non-printable characters
2) An example of a reproducing problem command

Then I will try to fix the problem

**Comment by liderman** [comment]
Without an example it is not clear how to fix it
